[build]
  publish = "public"
  command = "hugo --gc --minify --themesDir ../.."

[build.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENABLEGITINFO = "true"
HUGO_THEME = "repo"
HUGO_BASEURL = "/"

[context.production.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
