baseURL: https://example.com
languageCode: en-us
title: Jane Doe
theme: minimalist-theme
themesDir: ../..
disableHugoGeneratorInject: true
enableRobotsTXT: true

paginate: 3
favicon: /favicon.png

menu:
  main:
    - pageRef: /
      name: Home
      url: /
      weight: 1
    - pageRef: projects
      name: Projects
      url: /projects/
      weight: 2
    - pageRef: blog
      name: Blog
      url: /blog/
      weight: 3
    - pageRef: about
      name: About
      url: /about/
      weight: 4

markup:
  tableOfContents:
    endLevel: 3
  highlight:
    lineNos: true

params:
  title: Jane's Doe
  description: This is Jane's Doe portfolio
  images:
    - /images/author.jpg
  twitter: https://twitter.com


  gtm_id: GTM-xxxxxxx
  googleAnalytics: G-MEASUREMENT_ID

  # Hero section
  hero:
    title: >
      # I'm Jane Doe.
    description: A frontend web developer based in London.
    name: Jane Doe
    body: Lorem ipsum dolor sit amet consectetur adipiscing elit donec morbi lectus nisi egestas proin amet rhoncus sceleris lorem feugiat amet hac ornar morbi lectus.
    image: /images/author.jpg

  # Services section
  services:
    enable: true
    topTitle: Services
    title: Layout design and frontend development
    service:
      - content: >
          ### Web Design

          Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod
          tempor invidunt ut labore et dolore magna aliquyam erat.
      - content: >
          ### Web development

          Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod
          tempor invidunt ut labore et dolore magna aliquyam erat.
      - content: >
          ### Web management

          Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod
          tempor invidunt ut labore et dolore magna aliquyam erat.

  # Projects section
  projects:
    enable: true
    topTitle: Recent work
    title: Projects
    buttonTarget: projects

  # Blog section
  blog:
    enable: true
    topTitle: Recent Posts
    title: Blog
    buttonTarget: blog

  # CTA section
  cta:
    enable: true
    content: Let's Build Something Together

  # Contact
  contact:
    enable: true
    content: Feel free to reach out if you're looking for a developer, have a question, or just want to connect.
    email: janedoe@email.com
    btnName: Mail me

  # Social networks on footer
  github: https://github.com
  linkedin: https://linkedin.com
  twitter: https://twitter.com
  instagram: https://instagram.com
  facebook: https://facebook.com
  dribbble: https://dribbble.com
