baseURL = '/'
languageCode = 'en-us'
title = 'Jane Doe'
themesDir = "themes"
theme = "minimalist-theme"

paginate = 3

[menu]
[[menu.main]]
  pageRef='/'
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  pageRef='projects'
  name = 'Projects'
  url = '/projects/'
  weight = 2
[[menu.main]]
  pageRef='blog'
  name = 'Blog'
  url = '/blog/'
  weight = 3
[[menu.main]]
  pageRef="about"
  name = 'About'
  url = '/about/'
  weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 3
