baseURL: /
languageCode: en-us
title: Jane Doe
theme: minimalist-theme
themesdir: "../.."
paginate: 3
googleAnalytics: G-MEASUREMENT_ID

menu:
  main:
    - pageRef: /
      name: Home
      url: /
      weight: 1
    - pageRef: projects
      name: Projects
      url: /projects/
      weight: 2
    - pageRef: blog
      name: Blog
      url: /blog/
      weight: 3
    - pageRef: about
      name: About
      url: /about/
      weight: 4

markup:
  tableOfContents:
    endLevel: 3

params:
  title: Jane's Doe
  description: This is Jane's Doe portfolio
  images:
  - author.jpg

  # Services section
  services:
    enable: true

  # Projects section
  projects:
    enable: true

  # Blog section
  blog:
    enable: true

  # CTA section
  cta:
    enable: true

  # Contact
  contact:
    enable: true
    content: Feel free to reach out if you're looking for a developer, have a question, or just want to connect
    email: janedoe@email.com
    btnName: Mail me

  # Social networks on footer
  github: https://github.com
  linkedin: https://linkedin.com
  twitter: https://twitter.com
  instagram: https://instagram.com
  facebook: https://facebook.com
  dribbble: https://dribbble.com
